[package]
name = "regicide-rl"
version = "0.1.0"
authors = ["askepen <aske@daske.dk>"]
edition = "2018"

[profile.release]
debug = true

[dependencies]
rand = "0.8.5"
itertools = "0.10.2"
mcts = "0.3.0"
arrayvec = {git = "https://github.com/pYtoner/arrayvec/", features = ["copy"] }
